package at.crimsonbit.nodesystem.gui.settings;

public enum GraphSettings {

	COLOR_NODE_ACTIVE, COLOR_PORT_INPUT, COLOR_PORT_OUTPUT, COLOR_CURVE_DEFAULT,
	COLOR_TEXT_COLOR, COLOR_BACKGROUND, COLOR_BACKGROUND_LINES, SETTING_CURVE_WIDTH,
	SETTING_CURVE_CURVE,
	SETTING_SHADOW_WIDTH, SETTING_SHADOW_HEIGHT, SETTING_SHADOW_RADIUS, COLOR_SHADOW_COLOR,
}
