package at.crimsonbit.nodesystem.gui.color;

public enum GColors {
	COLOR_NODE_TRIANGLE_DEFAULT, COLOR_NODE_TRIANGLE_HOVERED, COLOR_SELECTION, COLOR_NODE, COLOR_NODE_ACTIVE, COLOR_PORT_INPUT, COLOR_PORT_OUTPUT, COLOR_CURVE_DEFAULT, COLOR_TEXT_COLOR, COLOR_BACKGROUND, COLOR_BACKGROUND_LINES, COLOR_SHADOW_COLOR, COLOR_ACTIVE_TOGGLED;

}
